version: "3"
services:
  wireguard:
    # image: linuxserver/wireguard:latest
    build: ./build_wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Brussels
      - PUID=${USERID}
      - PGID=${USERID}
      - PEERS=0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - DEBIAN_FRONTEND=noninteractive
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 1194:1194/udp
    restart: always
    volumes:
      - /lib/modules:/lib/modules
      - ./wg-server:/config:ro
  ui:
    image: ngoduykhanh/wireguard-ui:latest
    user: ${USERID}:${USERID}
    # cap_add:
    #   - NET_ADMIN
    # network_mode: host
    ports:
      - 5000:5000
    environment:
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - WGUI_ENDPOINT_ADDRESS=${SERVERURL}
      - WGUI_SERVER_INTERFACE_ADDRESSES=${INTERNAL_SUBNET}
      - WGUI_SERVER_LISTEN_PORT=${SERVERPORT}
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
      - WGUI_SERVER_POST_UP_SCRIPT=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
      - WGUI_SERVER_POST_DOWN_SCRIPT=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
    volumes:
      - ./wg-ui-db:/app/db
      - ./wg-server:/etc/wireguard